import { IProduct } from 'app/shared/model/product.model';

export const products: IProduct[] = [
  {
    id: 1,
    name: 'Dịch vụ gỡ giới hạn 12 tháng tham gia nhóm Google',
    price: 50000,
    newPrice: 20000,
    discount: 60,
    imageUrl: '/content/images/chat-GPT-plus.webp',
    slug: 'dich-vu-go-gioi-han-12-thang-tham-gia-nhom-google',
  },
  {
    id: 2,
    name: 'Tăng Tim Tiktok Người Việt Thật',
    price: 22000,
    newPrice: 830000,
    discount: 65,
    imageUrl: '/content/images/chat-GPT-plus.webp',
    slug: 'tang-tim-tiktok-nguoi-viet-that',
  },
  {
    id: 3,
    name: 'Kích hoạt License Michanger Plus 1 Tháng',
    price: 300000,
    newPrice: 250000,
    discount: 17,
    imageUrl: '/content/images/chat-GPT-plus.webp',
  },
  {
    id: 4,
    name: 'Gia Hạn Canva Pro Chính Chủ (1 Tháng)',
    price: 108333,
    newPrice: 16000,
    discount: 85,
    imageUrl: '/content/images/chat-GPT-plus.webp',
  },
  {
    id: 5,
    name: 'Dịch vụ gỡ giới hạn 12 tháng tham gia nhóm Google',
    price: 50000,
    newPrice: 20000,
    discount: 60,
    imageUrl: '/content/images/chat-GPT-plus.webp',
  },
  {
    id: 6,
    name: 'Tăng Tim Tiktok Người Việt Thật',
    price: 22000,
    newPrice: 830000,
    discount: 65,
    imageUrl: '/content/images/chat-GPT-plus.webp',
  },
  {
    id: 7,
    name: 'Kích hoạt License Michanger Plus 1 Tháng',
    price: 300000,
    newPrice: 250000,
    discount: 17,
    imageUrl: '/content/images/chat-GPT-plus.webp',
  },
  {
    id: 8,
    name: 'Gia Hạn Canva Pro Chính Chủ (1 Tháng)',
    price: 108333,
    newPrice: 16000,
    discount: 85,
    imageUrl: '/content/images/chat-GPT-plus.webp',
  },
];
